export {default as cntBtn} from './cntBtn'
export {default as footer} from './footer'
export {default as blackBg} from './blackBg'
export {default as linesSize} from './linesSize'
export {default as Dropdown} from './Dropdown'
export {default as NavbarPos} from './navbarPos'
export {default as footerScrollbar} from './footerScrollbar'
export {default as Nav} from './Nav'
export {default as CntPopup} from './CntPopup'
export {default as btnSound} from './btnSound'
export {default as scrollTo} from './scrollTo'
export {default as activeLink} from './activeLink'
export {default as MoreNews} from './MoreNews'
export {default as moreBtn} from './moreBtn'

