export {default as detectRouter} from './detectRouter'
export {default as Resize} from './Resize'
export {default as splitLines} from './splitLines'
export {default as getExtension} from './getExtension'
export {default as langCurrentPage} from './lang'
